CREATE TABLE USER (
user_id INT AUTO_INCREMENT  PRIMARY KEY,
user_name VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
secret_code VARCHAR(50) NOT NULL
);

CREATE TABLE FEEDBACK (
feedback_id INT AUTO_INCREMENT  PRIMARY KEY,
feedback VARCHAR(100) NOT NULL,
user_id int NOT NULL,
FOREIGN KEY (user_id) REFERENCES USER(user_id)
);